### ISSUE TITLE
Server disconnect 

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [TragicNeko/TragicMC3#1]
Hi, I get this and the connection to the server is terminated (this is singleplayer btw)

[16:08:18] [Netty Server IO #1/ERROR] [FML]: There was a critical exception handling a packet on channel tragicmc
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[guava-21.0.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:120) ~[FMLOutboundHandler$OutboundTarget$3.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) ~[SimpleNetworkWrapper.class:?]
	at tragicneko.tragicmc.capabilities.Achromy.onAchromyUpdate(Achromy.java:545) ~[Achromy.class:?]
	at tragicneko.tragicmc.events.EventUpdateCapabilities.onCapabilityUpdate(EventUpdateCapabilities.java:44) ~[EventUpdateCapabilities.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4036_EventUpdateCapabilities_onCapabilityUpdate_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[16:08:18] [Netty Server IO #1/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated

**Comment by assasinwar9** [comment]
can confirm this is a thing >.> would likely look into it myself if this was open source, but its not and id like to not get kicked from my server every 3rd use of the divine ability "bubble" at the very least <.< ... otherwise i do love this mod!

**Comment by TragicNeko** [comment]
I'd need more context as that is a generic crash and the codebase has changed since then. Does this only happen on Ability use? Is this affecting both single player and playing on a server? Is this the latest 1.12 preview version or the latest 1.12 release version? Is this with the mod by itself or in a larger modpack? Sorry for a late reply but I only got an email for the follow-up comment.

**Comment by assasinwar9** [comment]
so from my experience (limited as it is atm with the crash in question) it ONLY happens when activating the ability , i have not been able to test if its just bubble or if its all ability's , and i have not (yet) tested if it crashes on a "singleplayer instance" .... but i am indeed running it on a modpack, 

one thing iv noted is that the crash "more of a disconnect from server then a outright hard crash imo" is not "completely consistent" ... in other words i can activate bubble 3 times out of around 4 times... but at least one of those 4 times it will boot me from the server with... as far as i can tell the exact same error etc :/

as for the installed version of tragicmc3 , its 1.12.2-1.57.5258 , if you think i should update and try on the alpha version that is available then i will give it a shot! but i would like to be told if you think it would help or not... i am hosting a server for this for others so i want to make sure its going to be "a good idea" etc

and hopefully i can do some more "testing" to try and help! sadly iv been sick with some form of colitis for a lil more then 3 months so my brain is pretty "drowned" atm

and i will say that your reply was not late lol, its not like this is discord etc so i would expect you to only get email notifications etc!
i do appreciate your swift response and "general attitude" tho!

**Comment by TragicNeko** [comment]
Crashes like these are hard to track sometimes so having more context is always nice. It seems like if its disconnecting then its a client-side issue or an issue with parsing the network message. However, I may have also already fixed it in the current codebase since then. As it hasn't been crashing like that for me in all my playtesting, it's difficult for me to test it myself. I'd say you can definitely try the alpha version that's out and see if it remedies it in a single player environment. I don't want you to accidentally break stuff by updating the whole server to it and then going back to the older version afterwards. If you can check the log and see if that is the only crash on the server, and there isn't one on the server itself that's separate that could help as well. Thank you, I try to reply to stuff like this in at least a meaningful amount of time :D I hope you feel better soon too

**Comment by assasinwar9** [comment]
so i.... went ahead and made a "complete copy" of both the server AND client side etc, removed the config for your mod (so it will be updated properly and thus no problems) and removed the old version from both sides, n downloaded the alpha to test it etc..... got a crash before server actually finishes starting up... i have went and downloaded the crashlog , where would you like me to put it etc, and if you want i can include just the "crash cause" or if you want i can upload the whole log of course....

and im sorry if my msgs are "hard to read" since... my brain is pretty "toasted" and its hard to format like i normally do lol

and i appreciate the kind words etc, thankfully i now have 2 appointments setup to "check if i need the actual specialist exams"
so hopefully this gets fixed soon lol

**Comment by TragicNeko** [comment]
You can put the crash log in a pastebin and link it here I believe. I'll investigate it more when I can. It's no worry, it's not hard to read at all. I do hope all goes well for you with your appointments.

**Comment by assasinwar9** [comment]
https://pastebin.com/mgreJCKk

there you go, mind thats on the server side... didnt get to try on the client since no point if the server crashes before its up lol

**Comment by TragicNeko** [comment]
That's a simple crash related to the new type of weapons, so I'll push a new Alpha release soon to fix that. After that you should be good to test out if the previous crash still occurs.

**Comment by assasinwar9** [comment]
nice! if you can , just let me know when the alpha release is out and ill get to testing it!

**Comment by assasinwar9** [comment]
so just a heads up.... i dont know how or why but i used bubble like 7-9 times just now and no server disconnect..... im thinking maybe its a "instance" thing messing up or something... aka if i restart either the server or my client it "fixes" or something? since i changed legit nothing at all... to my memory at least.. am sick tho

**Comment by assasinwar9** [comment]
ok so quick update, i had the disconnect again, and then did some light testing.... only thing diffrent is i had a iron backpack in my inventory (this case hotbar) as i activated bubble..... maybe just a coincidence but its the only thing i have seen that "corrosponds" to the disconnect..... iron backpack from the iron backpacks mod..... tested it 3 times with it "put away" and no disconnect.... but had been having no disconnects at all TILL i put the iron backpack in my inv... hope that helps ?

annnnnnd it happened again even with no iron backpack so im leaning on some sort of instance thing...... again lol

**Comment by assasinwar9** [comment]
ok so been a bit, finally got a little better sickness wise, tested the new "TragicMC 3 - Wilds Alpha Preview 2 - v1.62.5774" and... can confirm activating the abillity still server disconnects, also even in singleplayer... and it was not even bubble, burst this time.... so ya...

**Comment by LamHK420** [comment]
I have this issue too
